sudo: required
language: java
jdk: oraclejdk8
script:
- ./gradlew lint
- ./gradlew test
- cat tron > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- cat tron
addons:
  ssh_known_hosts:
  - 47.93.9.236:22008
skip_build:
- README.md
- LICENSE
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: feature/deploy
before_install:
- openssl aes-256-cbc -K $encrypted_e5855cb9e09c_key -iv $encrypted_e5855cb9e09c_iv
  -in tron.enc -out tron -d
