sudo: required
language: java
jdk: oraclejdk8
script:
- sh tron.sh
- ./gradlew lint
- ./gradlew test
addons:
  ssh_known_hosts:
  - 47.93.9.236:22008
skip_build:
- README.mdï¼š
- LICENSE
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: addtestng
before_install:
- openssl aes-256-cbc -K $encrypted_e5855cb9e09c_key -iv $encrypted_e5855cb9e09c_iv
  -in tron.enc -out tron -d

after_deploy:
  - ./gradlew stest
