version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/java-tron
    steps:
    - checkout
    - run: curl http://60.205.215.34/Daily_Build_Task_Report